version: "1.0"

services:
   backend:
      build: .
      ports:
         - 3001:3001
      environment:
         - DB_HOST=db
      volumes:
         - .:/backend
      container_name: backend
      restart: always
      depends_on:
         - db

   db:
      image: mysql
      ports:
         - 3306:3306
      environment:
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      restart: always
      container_name: mysql

